import type { ProviderDefinition } from '@dudgital/shared'

const authTs = `import { betterAuth } from 'better-auth'

// @dudgital/provider-better-auth
export const auth = betterAuth({
  emailAndPassword: { enabled: true },
})
`

const routeTs = `import { auth } from '@/lib/auth'
import { toNextJsHandler } from 'better-auth/next-js'

// Generated by Dudgital
export const { GET, POST } = toNextJsHandler(auth)
`

export const betterAuthProvider: ProviderDefinition = {
  id: 'better-auth',
  name: 'Better Auth',
  modules: ['auth'],
  frameworks: ['nextjs'],
  npmPackages: {
    nextjs: ['better-auth'],
  },
  env: {
    nextjs: {
      BETTER_AUTH_SECRET: 'generate_a_long_random_secret',
      BETTER_AUTH_URL: 'http://localhost:3000',
    },
  },
  files: {
    nextjs: [
      {
        path: 'src/lib/auth.ts',
        content: authTs,
        marker: '@dudgital/provider-better-auth',
        mode: 'ensure',
      },
      {
        path: 'src/app/api/auth/[...all]/route.ts',
        content: routeTs,
        marker: 'Generated by Dudgital',
        mode: 'ensure',
      },
    ],
  },
  doctor: {
    nextjs: [
      { type: 'packageJsonDep', packages: ['better-auth'] },
      {
        type: 'envKeysNamed',
        path: '.env.local',
        keys: ['BETTER_AUTH_SECRET', 'BETTER_AUTH_URL'],
      },
      { type: 'fileExists', path: 'src/lib/auth.ts' },
      { type: 'fileExists', path: 'src/app/api/auth/[...all]/route.ts' },
    ],
  },
  nextSteps: [
    'Set BETTER_AUTH_SECRET to a strong random value',
    'Configure your database adapter per Better Auth docs',
    'Run: dg doctor',
  ],
}
