import type { ProviderDefinition } from '@dudgital/shared'

const nextMiddleware = `import { clerkMiddleware } from '@clerk/nextjs/server'

// @dudgital/provider-clerk
export default clerkMiddleware()

export const config = {
  matcher: [
    '/((?!_next|[^?]*\\\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)',
    '/(api|trpc)(.*)',
  ],
}
`

const nextSignIn = `export default function SignInPage() {
  return (
    <main style={{ padding: 48 }}>
      <h1>Sign in</h1>
      <p>Wire Clerk &lt;SignIn /&gt; here after setting env keys. Generated by Dudgital.</p>
    </main>
  )
}
`

const laravelMiddleware = `<?php
// @dudgital/provider-clerk
// Placeholder: install official Clerk Laravel SDK and register middleware per Clerk docs.
namespace App\\Http\\Middleware;

use Closure;
use Illuminate\\Http\\Request;

class ClerkAuthenticate
{
    public function handle(Request $request, Closure $next)
    {
        return $next($request);
    }
}
`

export const clerkProvider: ProviderDefinition = {
  id: 'clerk',
  name: 'Clerk',
  modules: ['auth'],
  frameworks: ['nextjs', 'laravel'],
  npmPackages: {
    nextjs: ['@clerk/nextjs'],
  },
  composerPackages: ['clerk/clerk-sdk-php'],
  env: {
    nextjs: {
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: 'pk_test_REPLACE_ME',
      CLERK_SECRET_KEY: 'sk_test_REPLACE_ME',
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: '/sign-in',
      NEXT_PUBLIC_CLERK_SIGN_UP_URL: '/sign-up',
    },
    laravel: {
      CLERK_PUBLISHABLE_KEY: 'pk_test_REPLACE_ME',
      CLERK_SECRET_KEY: 'sk_test_REPLACE_ME',
    },
  },
  files: {
    nextjs: [
      {
        path: 'middleware.ts',
        content: nextMiddleware,
        marker: '@dudgital/provider-clerk',
        mode: 'ensure',
      },
      {
        path: 'src/app/sign-in/[[...sign-in]]/page.tsx',
        content: nextSignIn,
        marker: 'Generated by Dudgital',
        mode: 'ensure',
      },
    ],
    laravel: [
      {
        path: 'app/Http/Middleware/ClerkAuthenticate.php',
        content: laravelMiddleware,
        marker: '@dudgital/provider-clerk',
        mode: 'ensure',
      },
    ],
  },
  doctor: {
    nextjs: [
      { type: 'packageJsonDep', packages: ['@clerk/nextjs'], message: '@clerk/nextjs installed' },
      {
        type: 'envKeysNamed',
        path: '.env.local',
        keys: ['NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY', 'CLERK_SECRET_KEY'],
      },
      { type: 'fileExists', path: 'middleware.ts' },
    ],
    laravel: [
      { type: 'composerDep', packages: ['clerk/clerk-sdk-php'] },
      {
        type: 'envKeysNamed',
        path: '.env',
        keys: ['CLERK_PUBLISHABLE_KEY', 'CLERK_SECRET_KEY'],
      },
      { type: 'fileExists', path: 'app/Http/Middleware/ClerkAuthenticate.php' },
    ],
  },
  nextSteps: [
    'Add real Clerk API keys from https://dashboard.clerk.com',
    'Restart your dev server',
    'Run: dg doctor',
  ],
}
